Local changes from 2017 not committed, it seems

diff --git a/vital-backup b/vital-backup
--- a/vital-backup
+++ b/vital-backup
@@ -4,47 +4,78 @@
 # vital-backup - backup absolutely key data to multiple destinations
 # 
 
+VERSION="2015.0807.01"
+
 # Read targets to backup to from this file
-CONFIG_FILE=$HOME/bin/vital-backup-config.txt
+CONFIG_FILE=$HOME/.vital-backup.conf
 
 # Tar parameters to create an archive. Specify compression type, or not, here
 # create, verbose, Sparse, compress (bzip2), a new file..
-CONFIG_TAR_PARAMETERS="cvSf"
+CONFIG_TAR_PARAMETERS="cvS"
 
 # Match the extension to your tar parameters: .tar, .tgz, .tbz, etc.
-CONFIG_FILE_EXT="tar"
+CONFIG_TAR_EXT=".tar"
+
+CONFIG_RSYNC_PARAMETERS="--verbose --recursive --human-readable --relative"
+
+CONFIG_RSYNC_EXT=".rsync"
 
 # When not used, make this "." to separate other fields
-CONFIG_FILE_TAG=".usbstore."
+CONFIG_FILE_TAG="vital-backup."
+
+BACKUP_TO_ALL_TARGETS=true
 
 # Default count of sources and targets to zero, define an array for each
 SOURCES=0
 SOURCE_LIST=()
-SOURCE_TAR_LIST=""
+SOURCE_DIR_STRING=""
 
 EXCLUDES=0
 EXCLUDE_LIST=()
-EXCLUDE_TAR_LIST=""
+EXCLUDE_DIR_STRING=""
 
 TARGETS=0
 TARGET_DIR=()
 TARGET_NAME=()
+TARGET_METHOD=()
+
+SKIP_TARGETS=0
+SKIP_TARGETS_LIST=()
+CHECK_SKIPS=false
+
+#
+# Functions
+#
+
+function only_target {
+  echo "Backing up to one target"
+  BACKUP_TO_ALL_TARGETS=false
+  CLI_TARGET_NAME_VALID=false
+
+  echo "Error: only_target() this feature not completed."
+  exit 1
+}
+
+# Add a named target to an array of targets to skip
+function skip_target {
+
+  # If the parameter provided to this is not empty, append it to the array
+  if [[ ! -z $1 ]]
+  then
+    echo "Adding skip target $1"
+    SKIP_TARGETS=$((SKIP_TARGETS+1))
+    SKIP_TARGET_LIST+=("$1")
+    # Toggle this so we skip things when reading the config file
+    CHECK_SKIPS=true
+  else
+    echo "Error: You must supply a target name with --skip-target"
+    exit 1
+  fi
+}
 
 #
 # Command line processing
 #
-
-CLI_TARGET_NAME=${1:-"null"}
-
-if [[ $CLI_TARGET_NAME == "null" ]]
-then
-  echo "Backing up to all targets"
-  ALL_TARGETS=true
-else
-  echo "Backing up to one target"
-  ALL_TARGETS=false
-  CLI_TARGET_NAME_VALID=false
-fi
 
 # specify config file
 # debugging on
@@ -53,6 +84,24 @@ fi
 # add targets
 # tar, cp or rsync
 # include hour in datestamp, or not
+
+function usage {
+	echo "vital-backup $VERSION"
+	echo
+	echo "usage: vital-backup <options>"
+  echo
+  echo "Configuration is read from ~/.vital-backup.conf"
+	echo
+	echo
+  echo "    --target <target> Write to only this named target"
+  echo
+  echo "    --skip <target>   Skip a target from the config file"
+  echo
+  echo "    --list            Show the configuration file's contents"
+  echo
+}
+
+# Discard unwanted data on config lines
 
 function clean_trailing_input_line {
   # Truncate anything fields that follow our source directory
@@ -74,200 +123,378 @@ function clean_trailing_input_line {
   fi
 }
 
-# Check for access to config file
-if [[ ! -r $CONFIG_FILE ]]
-then
-  echo "Error: I can't read from $CONFIG_FILE"
-  exit 1
-fi
+#
+# Append a target from the config file to the target array
+#
 
-# Read each line of the config file
-while read INPUT_LINE
-do
-  # If the line is NOT a comment, treat it as a target
-  if [[ ${INPUT_LINE:0:1} != "#" ]]
+function add_target {
+
+  echo "DEBUG add_target() $1"
+  echo "DEBUG add_target() $2"
+  echo "DEBUG add_target() $3"
+  
+  # Increment the number of targets
+  TARGETS=$((TARGETS+1))
+
+  # The mounted directory location of the target storage
+  TARGET_DIR+=("$1")
+
+  # The config file name of the target
+  TARGET_NAME+=("$2")
+
+  # The method of backing up data to this target
+  TARGET_METHOD+=("$3")
+}
+
+#
+# Copy data via tar to a storage device
+#
+
+function backup_via_tar {
+
+set -x
+  echo "PERFORMING TAR BACKUP to ${TARGET_STRING}"
+
+  TARGET_STRING="${TARGET_DIR[$TARGET_IDX]}/${CONFIG_FILE_TAG}host-${HOSTNAME}-${USER}-${DATETIME}${CONFIG_TAR_EXT}"
+
+  echo tar $CONFIG_TAR_PARAMETERS $EXCLUDE_DIR_STRING -f ${TARGET_STRING} $SOURCE_DIR_STRING
+
+  tar $CONFIG_TAR_PARAMETERS $EXCLUDE_DIR_STRING -f ${TARGET_STRING} $SOURCE_DIR_STRING
+  echo "Completed attempt to tar to ${TARGET_STRING}"
+set +x
+}
+
+#
+# Copy data via rsync to a storage device
+#
+
+function backup_via_rsync {
+  echo "PERFORMING RSYNC BACKUP to ${TARGET_STRING}"
+
+  TARGET_STRING="${TARGET_DIR[$TARGET_IDX]}/${CONFIG_FILE_TAG}${HOSTNAME}-${USER}.${DATETIME}${CONFIG_RSYNC_EXT}"
+
+  # Create the target string directory on the target and write data into it
+  mkdir -p "${TARGET_STRING}"
+
+  # Verify we were able to write data to the target directory 
+  RESULT=$?
+  if [[ $RESULT != 0 ]]
   then
+    echo "Error: Can't make target directory ${TARGET_STRING}"
+    exit 1
+  else
 
-    # process a source to be backed up
-    if [[ ${INPUT_LINE:0:6} == "source" ]]
+    echo rsync $CONFIG_RSYNC_PARAMETERS $SOURCE_DIR_STRING ${TARGET_STRING}
+    rsync $CONFIG_RSYNC_PARAMETERS $SOURCE_DIR_STRING ${TARGET_STRING}
+  fi
+
+  echo "Completed attempt to rsync to ${TARGET_STRING}"
+
+}
+
+function load_config_file {
+
+  # Check for access to config file
+  if [[ ! -r $CONFIG_FILE ]]
+  then
+    echo "Error: I can't read from $CONFIG_FILE"
+    exit 1
+  fi
+
+  # Read each line of the config file
+  while read INPUT_LINE
+  do
+    # If the line is NOT a comment, treat it as a target
+    if [[ ${INPUT_LINE:0:1} != "#" ]]
     then
 
-      # Truncate "target " from the front of the line
-      INPUT_LINE=${INPUT_LINE:7}
+      #
+      # Config file: process a source directory to be backed up
+      #
 
-      # Remove extra fields or comments form our input line
-      clean_trailing_input_line
-
-      # If the source exists, add it to our list of targets
-      if [[ -a $INPUT_LINE ]]
+      if [[ ${INPUT_LINE:0:6} == "source" ]]
       then
+
+        # Truncate "target " from the front of the line
+        INPUT_LINE=${INPUT_LINE:7}
+
+        # Remove extra fields or comments form our input line
+        clean_trailing_input_line
+
+        # If the source exists, add it to our list of targets
+        if [[ -a $INPUT_LINE ]]
+        then
+          # Append this source to our array of sources
+          SOURCES=$((SOURCES+1))
+          SOURCE_LIST+=("$INPUT_LINE")
+
+          # Append this directory to a single string listing all sources for tar
+          #SOURCE_DIR_STRING="$SOURCE_DIR_STRING \"$INPUT_LINE\""
+          SOURCE_DIR_STRING="$SOURCE_DIR_STRING $INPUT_LINE"
+        else
+          if [[ ! -r $INPUT_LINE ]]
+          then
+            echo "WARNING: Source $INPUT_LINE is not accessible."
+          else
+            echo "WARNING: Source $INPUT_LINE does not exist."
+          fi
+        fi
+      fi
+
+      #
+      # Config file: Exclude an object from the filesystem
+      #
+
+      if [[ ${INPUT_LINE:0:7} == "exclude" ]]
+      then
+
+        # Truncate "exclude " from the front of the line
+        INPUT_LINE=${INPUT_LINE:8}
+
+        # Remove extra fields or comments form our input line
+        #clean_trailing_input_line
+
         # Append this source to our array of sources
-        SOURCES=$((SOURCES+1))
-        SOURCE_LIST[$SOURCES]="$SOURCE_LIST $INPUT_LINE"
+        EXCLUDES=$((EXCLUDES+1))
+        #EXCLUDE_LIST[$EXCLUDES]="$EXCLUDE_LIST $INPUT_LINE"
+        EXCLUDE_LIST+=("$INPUT_LINE")
 
         # Append this directory to a single string listing all sources for tar
-        SOURCE_TAR_LIST="$SOURCE_TAR_LIST $INPUT_LINE"
-      else
-        if [[ ! -r $INPUT_LINE ]]
-        then
-          echo "WARNING: Source $INPUT_LINE is not accessible."
-        else
-          echo "WARNING: Source $INPUT_LINE does not exist."
-        fi
+        EXCLUDE_DIR_STRING="$EXCLUDE_DIR_STRING --exclude=\"$INPUT_LINE\""
       fi
-    fi
 
-    # Exclude an object from the filesystem
-    if [[ ${INPUT_LINE:0:7} == "exclude" ]]
-    then
+      # 
+      # Config file: Process a destination target for this backup
+      #
 
-      # Truncate "exclude " from the front of the line
-      INPUT_LINE=${INPUT_LINE:8}
-
-      # Remove extra fields or comments form our input line
-      clean_trailing_input_line
-
-      # Append this source to our array of sources
-      EXCLUDES=$((EXCLUDES+1))
-      EXCLUDE_LIST[$EXCLUDES]="$EXCLUDE_LIST $INPUT_LINE"
-
-      # Append this directory to a single string listing all sources for tar
-      EXCLUDE_TAR_LIST="$EXCLUDE_TAR_LIST --exclude $INPUT_LINE"
-    fi
-
-    # Process a destination target for this backup
-    if [[ ${INPUT_LINE:0:6} == "target" ]]
-    then
-
-      # Truncate "target " from the front of the line
-      INPUT_LINE=${INPUT_LINE:7}
-
-      # Capture the name of this target by finding the space between name & tgt
-      SPACE_POS=$(expr index "$INPUT_LINE" " "})
-      if [[ $SPACE_POS -gt 0 ]]
+      if [[ ${INPUT_LINE:0:6} == "target" ]]
       then
-        # Capture just the target
-        TARGET_NAME_END=$((SPACE_POS-1))
-        TARGET_NAME_STRING=${INPUT_LINE:0:TARGET_NAME_END}
 
-        # Prune input so it's 
-        INPUT_LINE=${INPUT_LINE:SPACE_POS}
-      fi
+        # Truncate "target " from the front of the line
+        INPUT_LINE=${INPUT_LINE:7}
 
-      # Remove extra fields or comments form our input line
-      clean_trailing_input_line
-
-      # If the target exists, add it to our list of targets
-      if [[ -d $INPUT_LINE ]]
-      then
-        TARGETS=$((TARGETS+1))
-
-        # Append the target destination to its array TARGETS=$((TARGETS+1))
-        TARGET_DIR[$TARGETS]="$TARGET_DIR $INPUT_LINE"
-
-        # Append the target name to its array
-        TARGET_NAME[$TARGETS]="$TARGET_NAME $TARGET_NAME_STRING"
-
-        if [[ $TARGET_NAME_STRING == $CLI_TARGET_NAME ]]
+        # Capture the name of this target by finding the space between name & tgt
+        SPACE_POS=$(expr index "$INPUT_LINE" " "})
+        if [[ $SPACE_POS -gt 0 ]]
         then
-          CLI_TARGET_VALID=true
+          # Capture just the target
+          TARGET_NAME_END=$((SPACE_POS-1))
+
+          TARGET_NAME_STRING=${INPUT_LINE:0:TARGET_NAME_END}
+
+          # Prune input so it's 
+          INPUT_LINE=${INPUT_LINE:SPACE_POS}
         fi
-      else
-        if [[ ! -r $INPUT_LINE ]]
+
+        # Capture the type of target such as cp, tar or rsync
+        SPACE_POS=$(expr index "$INPUT_LINE" " "})
+        if [[ $SPACE_POS -gt 0 ]]
         then
-          echo "WARNING: Target $INPUT_LINE is not accessible."
+          # Capture just the target
+          TARGET_METHOD_END=$((SPACE_POS-1))
+
+          TARGET_METHOD_STRING=${INPUT_LINE:0:TARGET_METHOD_END}
+
+          # Prune input so it's 
+          INPUT_LINE=${INPUT_LINE:SPACE_POS}
+        fi
+
+        # Remove extra fields or comments form our input line
+        clean_trailing_input_line
+
+        # If the target exists, add it to our list of targets
+        if [[ -d $INPUT_LINE ]]
+        then
+
+          # default to no, add this target
+          SKIP_THIS=false
+   
+          # If we have one or more skips, check them
+          if [[ $SKIP_TARGETS -gt 0 ]]
+          then
+
+            # Process each memory stick one at a time
+            for IDX in $(seq 0 $SKIP_TARGETS)
+            do
+
+              # Toggle false if this target is in the skip list
+              #echo "|${SKIP_TARGET_LIST[$IDX]}|$TARGET_NAME_STRING|"
+              if [[ ${SKIP_TARGET_LIST[$IDX]} == $TARGET_NAME_STRING ]]
+              then
+                echo "Skipping $TARGET_NAME_STRING from config file."
+                SKIP_THIS=true
+              fi
+            done
+
+          fi
+
+          if [[ $SKIP_THIS != true ]]
+          then
+
+            add_target "$INPUT_LINE" "$TARGET_NAME_STRING" "$TARGET_METHOD_STRING"
+
+            # If the target is somethig other than null, then we have a valid tgt
+            if [[ $TARGET_NAME_STRING == $CLI_TARGET_NAME ]]
+            then
+              CLI_TARGET_VALID=true
+            fi
+          fi
         else
-          echo "WARNING: Target $INPUT_LINE does not exist."
+          if [[ ! -r $INPUT_LINE ]]
+          then
+            echo "WARNING: Target $INPUT_LINE is not accessible."
+          else
+            echo "WARNING: Target $INPUT_LINE does not exist."
+          fi
         fi
       fi
+
+    fi
+  done < $CONFIG_FILE
+}
+
+function validate_options {
+
+  # Bail out if we have no sources
+  if [[ $SOURCES == 0 ]]
+  then
+    echo "Error: There are no backup sources available."
+    exit 1
+  fi
+
+  # Bail out if we have no targets
+  if [[ $TARGETS == 0 ]]
+  then
+    echo "Error: There are no backup targets available."
+    exit 1
+  fi
+
+  # Bail out if the user requested a target name we can't find
+  if [[ $CLI_TARGET_VALID == false ]]
+  then
+    echo "Error: There is no target configured as $CLI_TARGET_NAME"
+    exit 1
+  fi
+
+}
+
+function report_sizes {
+
+  echo
+  echo "Backing up $SOURCES sources:"
+
+  SOURCES_COUNT=$((SOURCES-1))
+  for SOURCE_IDX in $(seq 0 $SOURCES_COUNT)
+  do
+    # Capture human readable size
+    DU_HUMAN=$(du -sh ${SOURCE_LIST[$SOURCE_IDX]} | awk '{print $1}')
+    # Report it in column 1 right-justified
+    printf "%10s" $DU_HUMAN
+    # Report name of source in column 2, left-justified, no size
+    echo " ${SOURCE_LIST[$SOURCE_IDX]}"
+
+    # Capture size of source in bytes
+    DU_BYTES=$(du -sb ${SOURCE_LIST[$SOURCE_IDX]} | awk '{print $1}')
+
+    # Add size of source to total sources size by bytes
+    TOTAL_DU_BYTES=$((TOTAL_DU_BYTES+DU_BYTES))
+  done
+
+  # Provide a total
+  if [[ $TOTAL_DU_BYTES -gt 0 ]]
+  then
+
+    # Use the non-floating point values to decide what to report
+    TOTAL_DU_KB=$(($TOTAL_DU_BYTES/1024))
+    TOTAL_DU_MB=$((TOTAL_DU_BYTES/1048576))
+    TOTAL_DU_GB=$((TOTAL_DU_BYTES/1073741824))
+
+    # Use bc to calculate floating point values
+    TOTAL_DU_KB_FP=$(echo "scale=2; $TOTAL_DU_BYTES / 1024" | bc )
+    TOTAL_DU_MB_FP=$(echo "scale=2; $TOTAL_DU_BYTES / 1048576" | bc )
+    TOTAL_DU_GB_FP=$(echo "scale=2; $TOTAL_DU_BYTES / 1073741824" | bc)
+
+    printf "%10s\n" "-----"
+
+    if [[ $TOTAL_DU_GB -gt 0 ]]
+    then
+      printf "%10s" $TOTAL_DU_GB_FP
+      echo " Gigabytes TOTAL"
+    elif [[ $TOTAL_DU_MB -gt 0 ]]
+    then
+      printf "%10s" $TOTAL_DU_MB_FP
+      echo " Megabytes TOTAL"
+    elif [[ $TOTAL_DU_KB -gt 0 ]]
+    then  
+      printf "%10s" $TOTAL_DU_KB_FP
+      echo " Kilobytes TOTAL"
+    elif [[ $TOTAL_DU_MB -gt 0 ]]
+    then
+      printf "%10s" $TOTAL_DU_BYTES
+      echo " Bytes TOTAL"
     fi
 
   fi
-done < $CONFIG_FILE
 
-# Bail out if we have no sources
-if [[ $SOURCES == 0 ]]
-then
-	echo "Error: There are no backup sources available."
-	exit 1
-fi
+  echo
 
-# Bail out if we have no targets
-if [[ $TARGETS == 0 ]]
-then
-	echo "Error: There are no backup targets available."
-	exit 1
-fi
+}
 
-# Bail out if the user requested a target name we can't find
-if [[ $CLI_TARGET_VALID == false ]]
-then
-  echo "Error: There is no target configured as $CLI_TARGET_NAME"
-  exit 1
-fi
+#----------------------------------------------------------------------------
+#
+# Command Line Options Processing
+#
+#----------------------------------------------------------------------------
 
-echo
-echo "Backing up $SOURCES sources:"
-for SOURCE_IDX in $(seq 1 $SOURCES)
+CMD_LIST=false
+
+while [ "$1" != "" ]
 do
-  # Capture human readable size
-  DU_HUMAN=$(du -sh ${SOURCE_LIST[$SOURCE_IDX]} | awk '{print $1}')
-  # Report it in column 1 right-justified
-  printf "%10s" $DU_HUMAN
-  # Report name of source in column 2, left-justified, no size
-  echo "${SOURCE_LIST[$SOURCE_IDX]}"
 
-  # Capture size of source in bytes
-  DU_BYTES=$(du -sb ${SOURCE_LIST[$SOURCE_IDX]} | awk '{print $1}')
+	case $1 in 
 
-  # Add size of source to total sources size by bytes
-  TOTAL_DU_BYTES=$((TOTAL_DU_BYTES+DU_BYTES))
+		# enable debugging output
+		-d | --debug )
+			DEBUG="yes";;
+
+		-l | --list)
+			CMD_LIST=true;;
+
+		--target )
+			shift
+      only_target $1;;
+
+		--skip)
+			shift
+      skip_target $1;;
+
+		-h | --help )
+		usage
+		exit 0;;
+
+		# Something we don't understand? show syntax and exit
+		* )
+		usage
+		exit 1;;
+	esac
+	shift
 done
 
-# Provide a total
-if [[ $TOTAL_DU_BYTES -gt 0 ]]
-then
+# Load sources, excludes and targets from config file
+load_config_file
 
-  # Use the non-floating point values to decide what to report
-  TOTAL_DU_KB=$(($TOTAL_DU_BYTES/1024))
-  TOTAL_DU_MB=$((TOTAL_DU_BYTES/1048576))
-  TOTAL_DU_GB=$((TOTAL_DU_BYTES/1073741824))
+# Validate that we have sources and targets to work with
+validate_options
 
-  # Use bc to calculate floating point values
-  TOTAL_DU_KB_FP=$(echo "scale=2; $TOTAL_DU_BYTES / 1024" | bc )
-  TOTAL_DU_MB_FP=$(echo "scale=2; $TOTAL_DU_BYTES / 1048576" | bc )
-  TOTAL_DU_GB_FP=$(echo "scale=2; $TOTAL_DU_BYTES / 1073741824" | bc)
-
-  printf "%10s\n" "-----"
-
-  # If we have values for
-
-  if [[ $TOTAL_DU_GB -gt 0 ]]
-  then
-    printf "%10s" $TOTAL_DU_GB_FP
-    echo " Gigabytes TOTAL"
-  elif [[ $TOTAL_DU_MB -gt 0 ]]
-  then
-    printf "%10s" $TOTAL_DU_MB_FP
-    echo " Megabytes TOTAL"
-  elif [[ $TOTAL_DU_KB -gt 0 ]]
-  then  
-    printf "%10s" $TOTAL_DU_KB_FP
-    echo " Kilobytes TOTAL"
-  elif [[ $TOTAL_DU_MB -gt 0 ]]
-  then
-    printf "%10s" $TOTAL_DU_BYTES
-    echo " Bytes TOTAL"
-  fi
-
-fi
-
-echo
+# Report sizes of source directories and total source volume
+report_sizes 
 
 if [[ $EXCLUDES -gt 0 ]]
 then
   echo "Excluding these $EXCLUDES objects:"
-  for EXCLUDE_IDX in $(seq 1 $EXCLUDES)
+
+  EXCLUDES_COUNT=$((EXCLUDES-1))
+  for EXCLUDE_IDX in $(seq 0 $EXCLUDES_COUNT)
   do
     echo "${EXCLUDE_LIST[$EXCLUDE_IDX]}"
   done
@@ -275,10 +502,12 @@ fi
 
 echo
 
-if [[ $ALL_TARGETS == true ]]
+if [[ $BACKUP_TO_ALL_TARGETS == true ]]
 then
   echo "Writing to $TARGETS targets:"
-  for TARGET_IDX in $(seq 1 $TARGETS)
+
+  TARGETS_COUNT=$((TARGETS-1))
+  for TARGET_IDX in $(seq 0 $TARGETS_COUNT)
   do
     echo "${TARGET_DIR[$TARGET_IDX]}"
   done
@@ -286,7 +515,6 @@ else
   echo "Writing to target $CLI_TARGET_NAME only."
 fi
 
-echo
 read -p "Ready ?" YESNO
 if [[ $YESNO != "y" && $YESNO != "Y" && $YESNO != "yes" ]]
 then
@@ -295,13 +523,9 @@ fi
 
 DATETIME=$(date +%Y-%m%d)
 
-function backup_to_tar {
-echo    time tar $CONFIG_TAR_PARAMETERS ${TARGET_STRING} $EXCLUDE_TAR_LIST $SOURCE_TAR_LIST
-  time tar $CONFIG_TAR_PARAMETERS ${TARGET_STRING} $EXCLUDE_TAR_LIST $SOURCE_TAR_LIST
-}
-
 # Process each memory stick one at a time
-for TARGET_IDX in $(seq 1 $TARGETS)
+TARGETS_COUNT=$((TARGETS-1))
+for TARGET_IDX in $(seq 0 $TARGETS_COUNT)
 do
 
   # Remove the leading space from this target array's name
@@ -309,13 +533,19 @@ do
 
   # Perform our backupt if we're writing to all targets or 
   # or this is our selected one
-  if [[ $ALL_TARGETS == true || ${THIS_TARGET_NAME} == $CLI_TARGET_NAME ]]
+  if [[ $BACKUP_TO_ALL_TARGETS == true || ${THIS_TARGET_NAME} == $CLI_TARGET_NAME ]]
   then
 
-    TARGET_STRING=${TARGET_DIR[$TARGET_IDX]}/host-${HOSTNAME}.by-user-${USER}.${DATETIME}${CONFIG_FILE_TAG}${CONFIG_FILE_EXT}
+    echo $TARGET_IDX ${TARGET_METHOD[$TARGET_IDX]}
 
-    backup_to_tar
+    case ${TARGET_METHOD[$TARGET_IDX]} in
+      "tar" )
+        backup_via_tar;;
 
+      "rsync" )
+        backup_via_rsync;;
+    esac
+    
     echo
   fi
 
